[SERVICE]
    Flush        2
    Daemon       Off
    Log_Level    warn
    Parsers_File parsers.conf

[INPUT]
    Name              tail
    Path              /var/log/nginx/access.log
    Parser            nginx_json
    Tag               nginx.access
    Refresh_Interval  5
    Mem_Buf_Limit     10MB
    Skip_Long_Lines   On

[OUTPUT]
    Name            opensearch
    Match           nginx.*
    Host            opensearch
    Port            9200
    Index           nginx-logs
    Logstash_Format On
    Logstash_Prefix nginx-logs
    Logstash_DateFormat %Y.%m.%d
    Time_Key        @timestamp
    Time_Key_Format %Y-%m-%dT%H:%M:%S%z
    Suppress_Type_Name On
    tls             Off
    tls.verify      Off
